version: "3"

services:

  base:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ./support/entrypoint
  
  dev:
    extends:
      file: docker-compose.yml
      service: base
    command: bash

  run:
    extends:
      file: docker-compose.yml
      service: base
    command: ["python3", "src/main.py"]
  
  test:
    extends:
      file: docker-compose.yml
      service: base
    command: ["pytest", "test"]
